server:
  port: 8080

zuul:
  routes:
    item:
      service-id: application
      path: /item/**
      url: http://${application-service:localhost}:8081/item/
    oauth:
      service-id: authorization
      path: /oauth/**
      url: http://${authorization-service:localhost}:8082/
    client:
      service-id: authorization
      path: /client/**
      url: http://${authorization-service:localhost}:8082/
    user:
      service-id: authorization
      path: /user/**
      url: http://${authorization-service:localhost}:8082/
    statistics:
      service-id: statistics
      path: /statistics/**
      url: http://${statistics-service:localhost}:8083/

logging:
  level:
    org.feeder: DEBUG
    org.springframework: WARN
    org.hibernate: WARN
